export const WALLET_RULES = {
  COIN_VALUE_INR: 1,
  MIN_REDEMPTION_COINS: 50,
  MAX_CUSTOMER_BALANCE_COINS: 100,
};

export const QR_RULES = {
  MAX_DAILY_SCANS_PER_CUSTOMER: 3,
};

export const FLYER_RULES = {
  COUPON_VALIDITY_HOURS: 96,
};

export const STREAK_RULES = {
  INACTIVE_DAYS_FOR_RESET: 3,
  BONUS_COINS: 10,
  BONUS_MILESTONE_DAYS: 10,
};

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
